### ISSUE TITLE
Block padding

### ISSUE THREAD

**Issue by ZenithRogue** [mrjacobbloom/scratch-themes-resources#1]
I am working on [a simple coloring theme for 3.0](https://github.com/NitroCipher/theme3) and I remembered that at one point you figured out how to change the block padding. When I tried to find the code, I discovered it was removed from the post. Do you still have/remember how it was done?

**Comment by mrjacobbloom** [comment]
it was done by running a find-and-replace in the actual Blockly code and running it a second time to recalculate everything, but I don't believe Blockly is exposed at all in 3.0

**Comment by mrjacobbloom** [comment]
Whenever I get back to my computer I'll see if I can find the actual code though

**Comment by mrjacobbloom** [comment]
Found it:

```javascript
// ==UserScript==
// @name         Padding try 1
// @version      0.1
// @description  try to futz with padding
// @author       NickyNouse
// @match        http://llk.github.io/scratch-vm/
// @grant        GM_getResourceText
// @resource     renderVerticalRaw https://raw.githubusercontent.com/LLK/scratch-blocks/develop/core/block_render_svg_vertical.js
// ==/UserScript==

(function() {
    var renderVertical = GM_getResourceText('renderVerticalRaw')
    .replace(/goog\.\w+\('[\w\.]+'\);/g, '') // remove Closure stuff
    .replace('Blockly.BlockSvg.MIN_BLOCK_Y = 12 * Blockly.BlockSvg.GRID_UNIT;',
             'Blockly.BlockSvg.MIN_BLOCK_Y = 8 * Blockly.BlockSvg.GRID_UNIT;');
    eval(renderVertical);
})();
```

**Comment by mrjacobbloom** [comment]
Again, there's no way to access the Blockly variable in scratch-gui so I'm not sure how to get this to work there

**Comment by ZenithRogue** [comment]
Thanks for the code! I will try to puzzle through it later. (hopefully I will find a way :P)
